name: ai_chat
description: AiChat - 角色扮演类微信聊天APP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  flutter_slidable: ^3.0.1
  intl: ^0.19.0
  uuid: ^4.2.1
  image_picker: ^1.0.7
  lpinyin: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/avatars/
